boostly/alerts/routes.py
# Contains all the routes specific to alerts - waitlistAlert
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from boostly import db
# from boostly.utils import cleanup     # Learn how sessions work, then enable and insert
from boostly.alerts.forms import WaitAlertForm, SelectAlerteesForm
from boostly.alerts.emailAlert import sendEmail
from boostly.models import TempWaitAlert, SentWaitAlert, MsgTmpl, AvailTimes, PrefTimes, ClientPref, Client, ClientCompany, Company
from flask_login import current_user, login_required
from datetime import datetime


alerts = Blueprint('alerts', __name__)

@alerts.route("/waitalert/<int:tempalertid>/<string:owneremail>", methods=['GET','POST'])
@login_required             # Needed for routes that can only be accessed after login
def newWaitAlert(tempalertid, owneremail):
    print("owneremail is " + owneremail + " and the logged in user is " + current_user.user_email)	# Might need to put userID check in there once it comes to multi-user on one device. But for now this is actually more efficient and secure

    form = WaitAlertForm()
    print(" What does current_user get...?" + str(current_user) + " with datatype: " + str(type(current_user)))
    # The form displays the message template information interspersed with dynamic notification information
    msg = MsgTmpl.query.get(1)
    print("Message retrieved: " + str(msg))

    context = dict()
    alert=TempWaitAlert()
    if tempalertid==0 and owneremail=="new":
        alert = TempWaitAlert(slot_length=0, slot_start_date_time=datetime.now())
    elif owneremail != current_user.user_email:                               # ** Put in if id=0 and string="" conditions, then ENABLE LATER
        abort(403)
    else:
        # If check is successful, then the alert belongs to current_user
        alert = TempWaitAlert.query.get_or_404(tempalertid)

    context['alertSubject1'] =  msg.subj1
    context['companyName'] =  current_user.coyowner.company_name
    context['alertSubject2'] =  msg.subj2
    context['alertBody1'] = msg.part1                                                   # Hi + [clientName]
    context['alertBody2'] = msg.part2                                                   # I’m contacting everyone on my waitlist as a
    context['slotLength'] = alert.slot_length                                            #slotLength
    context['alertBody3'] = msg.part3                                                   # min 
    context['bizType'] = ""                                                             #massage  
    context['slotDay'] = alert.slot_start_date_time.strftime("%w")                         # appointment is now available on
    context['slotDate'] = datetime.strptime(str(alert.slot_start_date_time.strftime("%d/%m/%y")),("%d/%m/%y"))
    context['alertBody4'] = msg.part4                                                   # starting at 
    context['slotStartTime'] = alert.slot_start_date_time.strftime("%H:%M")                # 
    context['alertBody5'] = msg.part5                                                   # \nIf you would like to book in please do so on this link
    context['alertBody6'] = msg.part6                                                   # Look forward to seeing you
    context['alertBody7'] = msg.part7
    context['alertBody8'] = msg.part8

    context['bookingURL'] = '[staff.bookURL]'

    if form.validate_on_submit():

        # Collect data from form and update TempWaitAlert
        # Combine start date and time to startDateTime

        alert.slot_start_date_time = datetime.combine(form.slotStartDate.data, form.slotStartTime.data)
        alert.slot_length = form.slotLength.data
        # Attach current_user.id to user_id
        alert.user_id = current_user.id
        alert.status = "draft"
        alert.msg_tmpl = msg.id
        last_updated = datetime.now()

        if tempalertid==0 and owneremail=="new":
            # This will be a new entry, so add to database and get new alertID
            try:
                db.session.add(alert)
                db.session.commit()
                db.session.refresh(alert)     # Allows me to get the company_id
                tempalertid = alert.id        # can i successfully get the id?
                print("The Alert id retrieved is : " + str(tempalertid))
            except Exception as err:
                raise err

        else:
            try:
                # Just update the existing alert entry
                db.session.commit()
            except Exception as err:
                raise err

        flash('Please select the alert recipients', 'success')
        return redirect(url_for('alerts.selectAlertees', tempalertid=tempalertid))

    elif request.method == 'GET':
        dbSlotDT = alert.slot_start_date_time

        context['slotDay'] = dbSlotDT.strftime("%A")
        context['slotDate'] = dbSlotDT.strftime("%d %b %Y")
        context['slotTime'] = dbSlotDT.strftime("%H:%M")
        context['slotLength'] = alert.slot_length

        form.slotStartDate.data = dbSlotDT
        form.slotStartTime.data = dbSlotDT
        form.slotLength.data = alert.slot_length

    return render_template('createAlert.html', title='Send a new waitlist notification', form=form, context=context, legend="New Waitlist Alert", alert=alert)


#########################################################################################################
##  Routes for selecting clients that we want to alert/notify
##----------------------------------------------------------------------------------------------------

@alerts.route("/waitalert/<int:tempalertid>/alertees", methods=['GET','POST'])
@login_required             # Needed for routes that can only be accessed after login
def selectAlertees(tempalertid):
    alert = TempWaitAlert.query.get_or_404(tempalertid)
    alertDayOfWeek = alert.slot_start_date_time.strftime("%A")  
    # Filter preftimes table to get all clientpref_ids of clients matching those days
    curr_companyid = current_user.companyid
    print("The current  company is " + str(curr_companyid))
    # Querying the database to get the intersection between the Company and the Client using the current_user's company id, then adding status filtering on top of that
    clients = Client.query.join(ClientCompany).join(Company).filter(Company.id==curr_companyid, Client.status == 'active')
    print("The clients are: " + str(clients))
    # print("alertDayOfWeek is " + str(alertDayOfWeek) + " with type " + str(type(alertDayOfWeek)))

    availhumans = []

    alertid = tempalertid
    #-- Now we present the data in the UI table
    form = SelectAlerteesForm()
    context = dict()
    context['slotAvailDay'] =  alert.slot_start_date_time.strftime("%A")  
    # context['lastAlerted'] =  		# To add last alerted
    # context['alertyesno'] = msg.part1
    if form.validate_on_submit():
        try:
            selectedClients = form.selectedClients.data.split(',')
            # We need to process the selected client ids here but for now let's just print it
            company_name =  current_user.coyowner.company_name
            for client in selectedClients:
                # print("Checking that this is a client of:" + str(client) + " with the right datatype " + str(type(client)))
                sendEmail(tempalertid, company_name, int(client), current_user)	# Sends email notification and creates a record in SentWaitAlert db table
            # Update parent alert with status of Sent
            alert.status = "sent"
            db.session.commit()
            print("The selected clients are" + str(selectedClients))

            flash('Notifications sent!', 'success')
            return redirect(url_for('alerts.alertHistory'))
        except Exception as err:
            raise err


    elif request.method == 'GET':
        for client in clients:
            inloop = ClientPref.query.join(PrefTimes).join(AvailTimes)\
                        .filter(AvailTimes.time_unit==alertDayOfWeek)\
                        .filter(ClientPref.client_id==client.id).all()
            if len(inloop) > 0:
                availhumans.append(client)

            print("Available humans inloop pulled are: " + str(availhumans))

    useremail = current_user.user_email
    return render_template('selectAlertees.html', useremail = useremail, availhumans=availhumans, alertid=alertid, alertDayOfWeek=alertDayOfWeek, clients=clients, title='Select the recipents of the alert', form=form, context=context, legend="Select the recipents of the alert", alert=alert)


@alerts.route("/waitalert/history", methods=['GET','POST'])
@login_required             # Needed for routes that can only be accessed after login
def alertHistory():

    curr_companyid = current_user.companyid
    print("The current company is " + str(curr_companyid))

    alerts = SentWaitAlert.query.filter(SentWaitAlert.sent_user_id==current_user.id).order_by(SentWaitAlert.last_updated.desc()).all()
    print("The alerts retrieved are " + str(alerts))

    sentClient = {}
    slotDetails = {}
    slotLength = {}
    alertStatus = {}
    lastUpdated = {}
    for alert in alerts:
        # Have to pull out all this information to be able to query Client db for name
        client = Client.query.get(alert.client_id)
        sentClient[alert] = client.first_name + " " + client.last_name

        slotDetails[alert] = alert.slot_start_date_time.strftime("%A, %d %b %Y")
        slotLength[alert] = str(alert.slot_length)
        alertStatus[alert] = alert.status
        lastUpdated[alert] = str(alert.last_updated)

        print("List of clients sent to: " + str(sentClient[alert]) + " with slot deets: " + str(slotDetails))
        

boostly/users/routes.py
# Contains all the routes specific to users - register, login, logout, account

from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from boostly import db, bcrypt
# from boostly.utils import cleanup     # Learn how sessions work, then enable and insert
from boostly.models import User, Company
from boostly.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from boostly.users.utils import saveImage


users = Blueprint('users', __name__)

@users.route("/register", methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    form = RegistrationForm()

    if form.validate_on_submit():
        try:
        # First create a new company
            company = Company(company_name=form.companyName.data)
            db.session.add(company)        # Adds company to db
            db.session.commit()         # Commits company to db
            db.session.refresh(company)     # Allows me to get the companyID
            companyid = company.id        # can i successfully get the id?
            print("The Companys id retrieved is : " + str(companyid))

            # Using Bcrypt to hash the password so that we don't store passwords in plain text
            hashedPW = bcrypt.generate_password_hash(form.userPassword.data).decode('utf-8')
            # Create an object user with the data collected from the form, passing in the hashed password (instead of cleartext)
            user = User(user_email=form.userEmail.data, timely_booking_url=form.timelyBookingURL.data, user_last_name=form.userLastName.data, user_first_name=form.userFirstName.data, user_password=hashedPW, companyid=companyid)
            user = User(user_email=form.userEmail.data, user_last_name=form.userLastName.data,  timely_booking_url=form.timelyBookingURL.data, user_first_name=form.userFirstName.data, user_password=hashedPW, companyid=companyid)
            db.session.add(user)        # Adds user to db
            db.session.commit()         # Commits user to db                   
            flash('Your account has been created. Please log into your account', 'success')
            return redirect(url_for('users.login'))
        except Exception as err:
            raise err

    errors = [{'field': key, 'messages': form.errors[key]} for key in form.errors.keys()] if form.errors else []
    return render_template('register.html', title='Sign up for your Boostly Account!', form=form, errors=errors)

@users.route("/login", methods=['GET','POST'])
def login(): 
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(user_email=form.userEmail.data).first()
        print("You have filtered data from your db, user = " + str(user))
        # Decrypt the password hash and check it against the users' password in the database
        # If they match, log the user in and remember their "remember me " choice
        if user and bcrypt.check_password_hash(user.user_password, form.userPassword.data):
            login_user(user, remember=form.userRemember.data)
            # If the user has been trying to access a specific page before logging in, redirect them to that page. Otherwise redirect them to home
            nextPage = request.args.get('next')
            return redirect(nextPage) if nextPage else redirect(url_for('main.dashboard'))
        else:
            flash('Login unsuccessful. Please check email and password', 'danger')
            return render_template('login.html', title='Log into your Boostly Account!', form=form)
    return render_template('login.html', title='Log into your Boostly Account!', form=form)


@users.route("/logout")
def logout():
    # Uses flask-login's logout_user function
    logout_user()
    return redirect(url_for('main.home')) 

@users.route("/account", methods=['GET','POST'])
@login_required
def account():
    form = UpdateAccountForm()
    coyID = current_user.companyid
    print("The coyID pulled is "+ str(coyID))
    current_company=Company.query.get(coyID)
    print("The current_company pulled is "+ str(current_company))
    if form.validate_on_submit():
        try:

            if form.uploadImage.data:
                # Saving the picture and updating the database with the hex-ed filename
                hexedImage = saveImage(form.uploadImage.data)
                current_user.user_image = hexedImage
                current_user.user_first_name = form.userFirstName.data
                current_user.user_last_name = form.userLastName.data
                current_user.user_email = form.userEmail.data
                current_company.company_name = form.companyName.data
                current_user.timely_booking_url = form.timelyBookingURL.data
                db.session.commit()
                flash('Your account has been updated', 'success')
                return redirect(url_for('users.account'))
        except Exception as err:
            raise err
        
    elif request.method == 'GET':
        form.companyName.data = current_company.company_name
        form.timelyBookingURL.data = current_user.timely_booking_url
        form.userFirstName.data = current_user.user_first_name
        form.userLastName.data = current_user.user_last_name
        form.userEmail.data = current_user.user_email

    userImage = url_for('static', filename='profilePics/' + current_user.user_image)
    return render_template('account.html', title='Your Boostly User Account', userImage=userImage, form=form)


boostly/templates/alertHistory.html
{% extends "layout.html" %}
	{% block content %}
	<div class="container">
		<link href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css" rel="stylesheet" />
		<!-- <script src="https://unpkg.com/gridjs/dist/gridjs.umd.js"></script> -->


		<div class="pt-3">
		  <h1>Your alert history</h1>
		  <p>We keep up to 3 weeks' worth of your alert history </p>
		  <hr>
		  <div id="table"></div>
		</div>

		<script type="module">
			// import { html, render } from 'https://unpkg.com/htm/preact/standalone.module.js';
			import { Grid, h } from "https://unpkg.com/gridjs?module";


		  const grid  = new Grid({

				columns: [
					{ id: 'client', name: 'Sent to' },
					{ id: 'slot_start_date_time', name: 'Slot Details' },
					{ id: 'slot_length', name: 'Slot length' },
					{ id: 'status', name: 'Status'},
					{ id: 'updated', name: 'Last Updated'},

					],

			data: [
				{% for alert in alerts %}
				{
					client: '{{ client[alert] }}',
					slot_start_date_time: '{{ details[alert] }}',
					slot_length: '{{ length[alert] }}',
					status: '{{ status[alert] }}',
					updated: '{{ updated[alert] }}',

				},
				{% endfor %}
			],
			search: {
				selector: (cell, rowIndex, cellIndex) => [0, 1, 4].includes(cellIndex) ? cell : null,
			},
			sort: true,
			pagination: true,
			language: {
				noRecordsFound: "You have not sent any notifications yet",
			}

			}).render(document.getElementById('table'));
		</script>
	</div>




{% endblock content %}



boostly/templates/dashboard.html
{% extends "layout.html" %}
	{% block content %}
 <style>
    /* Center the container */
    html, body {
      height: 100%;
      display: flex;
      align-items: center;
      justify-content: center;
      background-color: white;
      background-image: url('static/images/back_home.png');
      background-repeat: no-repeat;
		background-attachment: fixed;
		background-size: cover;
    }
  </style>
	<div class="container">
		<h1 style="text-align: center;">Kia ora, {{ current_user.user_first_name }}!</h1>
		<hr>
		<div class="container pt-4">
		 <div class="row mr-3">
		  <div class="col-md-3">
			<div class="card" style="width: 15rem; height: 27rem;">
			  <img src="https://boostly-site-images.s3.amazonaws.com/Wait%2BList-01_small.png" width=40% height=40% class="card-img-top" alt="Waitlist">
			  <div class="card-body">
				<h5 class="card-title">Notify Clients</h5>
				<p class="card-text">Click here to create a new alert for your waitlist.</p>
				<a href="{{ url_for('alerts.newWaitAlert', tempalertid=0, owneremail='new') }}" class="btn btn-submit">Create Alert</a>
			  </div>
			</div>
		  </div>
		  <div class="col-md-3">
			<div class="card" style="width: 15rem;height: 27rem;">
			  <img src="https://cdn2.hubspot.net/hubfs/62664/Top_8_tips_to_effective_client_management1.jpg" class="card-img-top" alt="Client Information">
			  <div class="card-body">
				<h5 class="card-title">Client Information</h5>
				<p class="card-text">View and manage client information.</p>
				<a href="{{ url_for('clients.displayClients') }}" class="btn btn-submit">View Information</a>
			  </div>
			</div>
		  </div>
		  <div class="col-md-3">
			<div class="card" style="width: 15rem;height: 27rem;">
			  <img src="https://commerce.beaboss.fr/assets/Img/BREVE/2016/6/305560/Relation-client-cles-federer-vos-clients-autour-votre-commerce-F.jpg" class="card-img-top" alt="Client Preferences">
			  <div class="card-body">
				<h5 class="card-title">Client Preferences</h5>
				<p class="card-text">Manage client preferences and settings.</p>
				<a href="{{ url_for('clients.displayClientPrefs') }}" class="btn btn-submit">Manage Preferences</a>
			  </div>
			</div>
		  </div>
		  <div class="col-md-3">
			<div class="card" style="width: 15rem;height: 27rem;">
			  <img src="https://imageio.forbes.com/specials-images/imageserve/63933ffe940d9c0caeb13be0/Marketing-strategy/960x0.jpg?height=626&width=711&fit=bounds" class="card-img-top" alt="Add New Client">
			  <div class="card-body">
				<h5 class="card-title">Add New Client</h5>
				<p class="card-text">Click here to add a new client to your list.</p>
				<a href="{{ url_for('clients.newClient') }}" class="btn btn-submit">Add Client</a>
			  </div>
			</div>
		  </div>
		</div>
		</div>
	</div>
	


	
{% endblock content %}



boostly/templates/home.html
<!-- This will soon be transferred to the home.html page, with the home.html page content swapped here -->

{% extends "layout.html" %}
{% block content %}
  <!-- Custom CSS -->
  <style>
    /* Center the container */
    html, body {
      height: 100%;
      display: flex;
      align-items: center;
      justify-content: center;
      background-color: white;
      background-image: url('static/images/back_home.png');
      background-repeat: no-repeat;
	  background-attachment: fixed;
	  background-size: cover;
    }
  </style>

		<div class="container mx-2 my-2">
			<img class = "logoLoginPage" src="../static/images/logo-03.png" alt="Logo">
			<!--form-->
			<form  method="POST" action="">
				<!-- # Hidden tag method adds a CSRF token -->
				{{ form.hidden_tag() }}

					<div class="form-group">
						{{ form.userEmail.label(class="form-control-label") }}
						{% if form.userEmail.errors %}
							{{ form.userEmail(class="form-control form-control-md is-invalid")}}
							<div class="invalid-feedback">
								{% for error in form.userEmail.errors %}
									<span> {{ error }} </span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.userEmail(class="form-control form-control-md") }}
						{% endif %}
					</div>
					<div class="form-group">
						{{ form.userPassword.label(class="form-control-label") }}
						{% if form.userPassword.errors %}
							{{ form.userPassword(class="form-control form-control-md is-invalid")}}
							<div class="invalid-feedback">
								{% for error in form.userPassword.errors %}
									<span> {{ error }} </span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.userPassword(class="form-control form-control-md") }}
						{% endif %}
					</div>
					<!--remember me check-box-->
					<div class = "d-flex justify-content-between align-items-center">
						<div class='form-check mb-0'>
							{{ form.userRemember(class="form-check-input") }}
							{{ form.userRemember.label(class="small form-check-label") }}
						</div>
					</div>
					<!--login button-->
				<div class="pt-3">
					{{ form.submit(class="btn btn-block btn-submit") }}
					<!--link to the registration page-->
				</div>
				<div class="text-center text-lg-start mt-1 pt-2">
					<small class="small mt-1 pt-0 mb-3">
						Don't have an account? <a class="link-primary" href="{{ url_for('users.register') }}">Sign up here</a>
					</small>
				</div>
			</form>
		</div>
{% endblock content %}




boostly/templates/index.html
{% extends "layout.html" %}
{% block content %}
	{% for task in tasks %}
<!--        Landing page-->

	{% endfor %}
{% endblock content %}

boostly/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- Putting JQuery here to see if this helps with loading scripts -->
	<script src="{{ url_for('static', filename='myscripts.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
    <!-- Testing to see if downgrading to 4.6 works for dropdowns.. it does!! -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <!-- Linking our custom CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
  	<script src="https://kit.fontawesome.com/2ca52e1c9f.js" crossorigin="anonymous"></script>


	{% if title %}
		<title>Boostly - {{ title }}</title>
	{% else %}
		<title>This is the new Homepage!</title>
	{% endif %}
	</head>

	<body>
		<!-- Navbar and Making it responsive  -->
		<header class="site-header">
		  <nav class="navbar navbar-expand-md navbar-dark back-color-nav fixed-top py-3" id="navbarToHide">
		    <div class="container">
		      <a class="navbar-brand mr-4" href="/">Boostly</a>
		      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
		        <span class="navbar-toggler-icon"></span>
		      </button>
		      <!-- Navbar Left Side -->

		      <div class="collapse navbar-collapse" id="">
		        <div class="navbar-nav mr-auto">
		        	{% if current_user.is_authenticated %}
		        		<a class="nav-item nav-link"  style="color:#424242;" href="{{ url_for('main.dashboard') }}">Dashboard</a>
		        	{% endif %}

		        </div>
		        <!-- Navbar Right Side -->
		        <div class="navbar-nav">
		        	<!-- # Using ginja2 conditional and using current_user.is_authenticated to check if user is logged in or not -->
		        	{% if current_user.is_authenticated %}
					<div class="dropdown">
						  <button class="btn dropdown-toggle" type="button" id="clientDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Your clients
						  </button>
						  <div class="dropdown-menu" aria-labelledby="clientDropdown">
							  <a class="dropdown-item" href="{{ url_for('alerts.newWaitAlert', tempalertid=0, owneremail='new') }}">Create alert</a>
						  	<a class="dropdown-item" href="{{ url_for('clients.newClient') }}">Add new client</a>
							<a class="dropdown-item" href="{{ url_for('clients.displayClients') }}">Client Information</a>
							<a class="dropdown-item" href="{{ url_for('clients.displayClientPrefs') }}">Client Preferences</a>
						  </div>
					</div>
		        		<a class="nav-item nav-link"  style="color:#424242;" href="{{ url_for('users.account') }}">Account</a>
		        		<a class="nav-item nav-link"  style="color:#424242;" href="{{ url_for('users.logout') }}">Logout</a>
		        	{% else %}
			          <a class="nav-item nav-link"  style="color:#424242;" href="{{ url_for('users.login') }}">Login</a>
			          <a class="nav-item nav-link"  style="color:#424242;" href="{{ url_for('users.register') }}">Register</a>
		          {% endif %}
		        </div>
		      </div>
		    </div>
		  </nav>
		</header>


		<main role="main">
		    	{% with messages = get_flashed_messages(with_categories=true) %}
		    		{% if messages %}
		    			{% for category, message in messages %}
		    				<div class="alert alert-{{ category }}">
		    						{{ message }}
		    				</div>
		    			{% endfor %}
		    		{% endif %}
		    	{% endwith %}
		      {% block content %}{% endblock %}
		</main>


		<!-- Optional JS for Bootstrap - jQuery first, then Popper.js, then Bootstrap -->

		<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script> -->
		<!-- <script src="https://unpkg.com/@popperjs/core@2"></script> -->
<!-- 		<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script> -->

		<!-- Again testing to see if 4.6 works.. it does!! -->


		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>


		 <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

	</body>
</html>

boostly/templates/login.html
<!-- This will soon be transferred to the home.html page, with the home.html page content swapped here -->

{% extends "layout.html" %}
{% block content %}
  <!-- Custom CSS -->
  <style>
    /* Center the container */
    html, body {
      height: 100%;
      display: flex;
      align-items: center;
      justify-content: center;
      background-color: white;
      background-image: url('static/images/back_home.png');
      background-repeat: no-repeat;
		background-attachment: fixed;
		background-size: cover;
    }
  </style>

		<div class="container mx-2 my-2">
			<img class = "logoLoginPage" src="../static/images/logo-03.png" alt="Logo">
			<!--form-->
			<form  method="POST" action="">
				<!-- # Hidden tag method adds a CSRF token -->
				{{ form.hidden_tag() }}

					<div class="form-group">
						{{ form.userEmail.label(class="form-control-label") }}
						{% if form.userEmail.errors %}
							{{ form.userEmail(class="form-control form-control-md is-invalid")}}
							<div class="invalid-feedback">
								{% for error in form.userEmail.errors %}
									<span> {{ error }} </span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.userEmail(class="form-control form-control-md") }}
						{% endif %}
					</div>
					<div class="form-group">
						{{ form.userPassword.label(class="form-control-label") }}
						{% if form.userPassword.errors %}
							{{ form.userPassword(class="form-control form-control-md is-invalid")}}
							<div class="invalid-feedback">
								{% for error in form.userPassword.errors %}
									<span> {{ error }} </span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.userPassword(class="form-control form-control-md") }}
						{% endif %}
					</div>
					<!--remember me check-box and forgot password link-->
					<div class = "d-flex justify-content-between align-items-center">
						<div class='form-check mb-0'>
							{{ form.userRemember(class="form-check-input") }}
							{{ form.userRemember.label(class="small form-check-label") }}
						</div>
					</div>
					<!--login button-->
				<div class="pt-3">
					{{ form.submit(class="btn btn-block btn-submit") }}
					<!--link to the registration page-->
				</div>
				<div class="text-center text-lg-start mt-1 pt-2">
					<small class="small mt-1 pt-0 mb-3">
						Don't have an account? <a class="link-primary" href="{{ url_for('users.register') }}">Sign up here</a>
					</small>
				</div>
			</form>
		</div>
{% endblock content %}


